# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # aliased to a recent 5.4.x version
  #- 5.4
  # aliased to a recent 5.5.x version
  #- 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  #- 7
  # hhvm
  #- hhvm

before_install:
  - sudo apt-get update > /dev/null
  - PHPVER=$(php -v | grep  -P --only-matching "\\d+" | head -n 1)
  - if [ 7 = $PHPVER ]; then GMP="php-gmp"; else GMP="php5-gmp";fi

install:
  - sudo apt-get install -y --force-yes $GMP
  - php -m

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
before_script:
  # - echo "extension = gmp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --no-interaction
  - mkdir -p build/logs
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - vendor/phpunit/phpunit/phpunit --configuration ./phpunit.travis.xml test

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# configure notifications (email, IRC, campfire etc)
notifications:
  email: "ashley@zf4.biz"